site_name: Introduction to Data Science
site_url: https://example.com/

theme:
  font:
    text: Glory
    code: Source Code Pro
  langage: en
  name: material
  logo: "https://upload.wikimedia.org/wikipedia/commons/4/45/Glider.svg"
  favicon: images/favicon.ico
  palette:
    scheme: default
    primary: orange
    accent: red
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - admonition
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mickaeltemporao
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mickaeltemporao
extra_css:
  - stylesheets/extra.css
# repo_url: https://github.com/mkdocs/mkdocs/

# Page tree
nav:
  - Home: index.md
  - syllabus.md
  - Activities:
    - activities/participation.md
    - activities/challenges.md
    - activities/project.md
  - Schedule:
    - schedule.md
    - Modules:
      - modules/introduction.md
      - modules/tools.md
      - modules/programming-1.md
      - modules/programming-2.md
      - modules/programming-3.md
      - modules/vizualization-1.md
      # - modules/causality.md
      # - modules/sampling.md
      # - modules/measurement.md
      # - modules/replication.md
    # - Semestre 2:
      # - modules/programming.md
      # - modules/statistics.md
      # - modules/variables.md
      # - modules/hypothesis.md
      # - modules/analysis.md
      # - modules/communication.md
  - Resources:
    - resources/onboarding.md
    - resources/coding.md
    - resources/writing.md
    - resources/misc.md
  - Chat: "https://gitter.im/ScPoBx/introduction-to-data-science"

copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><span property="dct:title">Introduction to Data Science</span> by <span property="cc:attributionName">Mickael Tempor√£o</span> is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a></p>
